echo "Welcome to the lctr Registry Debug Tool"
echo ""
echo "This tool combines lctr and mitmproxy in a single tmux session"
echo ""
echo "lctr tips:"
echo "'lctr image login -u <myuser> docker.io' to login to a registry such as Docker Hub"
echo "'lctr image pull alpine' to pull the image docker.io/library/alpine:latest"
echo "'lctr image push myuser/alpine alpine' to push the alpine image to docker.io/myuser/alpine:latest"
echo ""
echo "tmux tips:"
echo "'ctrl+b <down>' to navigate down a pane"
echo "'ctrl+b <up>' to navigate up a pane"
echo "'ctrl+b d' to quit (or exit all panes)"
